---
title: "Project 2 Report"
author: "Chanel Fraikin and Benjamin Kelly"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 3
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

```{r setup, include = FALSE}

#### Load necessary packages ####
# * These packages are not necessary to complete the assignment and or only used 
#   to provide an example. 
packages <- c("knitr", "kableExtra", "magrittr", "readr", "geosphere", "dplyr",
              "tidyr", "ggplot2", "scales", "leaflet", "htmltools",
              "cowplot")

install_me <- packages[!(packages %in% installed.packages()[, "Package"])]
if (length(install_me)) install.packages(install_me)

library(knitr)
library(kableExtra)
library(magrittr)
library(readr)
library(geosphere)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(leaflet)
library(htmltools)
library(cowplot)
```

# Global Trajectory
```{r obj1, message=FALSE, warning=FALSE, fig.width=10}
# Load Datasets
confirmed_ds<-read.csv("time_series_covid19_confirmed_global.csv", 
                       header=TRUE, stringsAsFactors=FALSE)
recovered_ds<-read.csv("time_series_covid19_recovered_global.csv", 
                       header=TRUE, stringsAsFactors=FALSE)
deaths_ds<-read.csv("time_series_covid19_deaths_global.csv", 
                    header=TRUE, stringsAsFactors=FALSE)

# Get totals per day through summation
confirmed_sum<-confirmed_ds%>%select(-(1:4))%>%summarise_all(sum)
recovered_sum<-recovered_ds%>%select(-(1:4))%>%summarise_all(sum)
death_sum<-deaths_ds%>%select(-(1:4))%>%summarise_all(sum)

# Merge datasets into one and add column for categories
dat <- rbind(confirmed_sum, recovered_sum, death_sum)
dat$dataset <- factor(c(rep("Confirmed", dim(confirmed_sum)[1]),
                        rep("Recovered", dim(recovered_sum)[1]),
                        rep("Deaths", dim(death_sum)[1])))

data_long <- gather(dat, Dates, SumCases, -dataset, factor_key=TRUE)

# Create Plot
ggplot(data_long, aes(x=Dates, y=SumCases, color=dataset)) + 
  scale_color_discrete(breaks=c("Confirmed", "Recovered", "Deaths")) +
  geom_point() + ggtitle("Global Trajectory for COVID-19") + 
  scale_x_discrete(breaks=c("X2.1.20","X3.1.20","X4.1.20", "X5.1.20"),
                   labels=c("Feb", "Mar", "Apr", "May")) +
  labs(y= "Cases", x = "Date") +
  scale_y_continuous(breaks=pretty_breaks(n=5), 
                     labels=scales::comma)

```

# Global Map
```{r obj2, message=FALSE, warning=FALSE, fig.width=9.5}
# Get data form last date which represents total
last_date <- names(confirmed_ds)[ncol(confirmed_ds)]
confirmed_last<-confirmed_ds%>%select(Province.State, Country.Region, 
                                      Lat, Long, starts_with(last_date))
recovered_last<-recovered_ds%>%select(Province.State, Country.Region, 
                                      Lat, Long, starts_with(last_date))
deaths_last<-deaths_ds%>%select(Province.State, Country.Region, 
                                Lat, Long, starts_with(last_date))

# Rename last column to make calling it easier
# because R...
names(confirmed_last)[ncol(confirmed_last)]<-"Count"
names(recovered_last)[ncol(recovered_last)]<-"Count"
names(deaths_last)[ncol(deaths_last)]<-"Count"

# Merge data
dat <- rbind(confirmed_last, recovered_last, deaths_last)
dat$dataset <- factor(c(rep("Confirmed", dim(confirmed_last)[1]),
                        rep("Recovered", dim(recovered_last)[1]),
                        rep("Deaths", dim(deaths_last)[1])))

# Create a palette that maps factor levels to colors
pal <- colorFactor(c("blue", "cyan", "red"),
                   domain = c("Confirmed", "Recovered", "Deaths"))

# Create interactive map
leaflet(dat) %>% addTiles() %>%
  addCircles(
    radius = ~sqrt(dat$Count)*1000,
    color = ~pal(dataset),
    stroke = TRUE, 
    fillOpacity = 0.4,
    group = ~dataset,
    label = paste(ifelse(dat$Province.State == "", 
                         dat$Country.Region, 
                         dat$Province.State)),
    popup = paste(dat$dataset, ": ", dat$Count, sep="")
    ) %>%
  addLayersControl(
    overlayGroups = c("Confirmed", "Recovered", "Deaths"),
    options = layersControlOptions(collapsed = FALSE)
    ) 
```

# Narrowing Down Hot Spots
```{r obj3, message=FALSE, warning=FALSE, fig.width=10}
# Combine Province/Country
confirmed_last$Location <- ifelse(confirmed_last$Province.State == "", 
                                  paste(confirmed_last$Country.Region), 
                                  paste(confirmed_last$Province.State,
                                    confirmed_last$Country.Region, sep=", "))
recovered_last$Location <- ifelse(recovered_last$Province.State == "", 
                                  paste(recovered_last$Country.Region), 
                                  paste(recovered_last$Province.State,
                                    recovered_last$Country.Region, sep=", "))
deaths_last$Location <- ifelse(deaths_last$Province.State == "", 
                               paste(deaths_last$Country.Region), 
                               paste(deaths_last$Province.State,
                                 deaths_last$Country.Region, sep=", "))

confirmed_totals<-arrange(select(confirmed_last, Location, Count), -Count)
recovered_totals<-arrange(select(recovered_last, Location, Count), -Count)
deaths_totals<-arrange(select(deaths_last, Location, Count), -Count)

# Rename columns so they do not get merged
names(confirmed_totals)<-c("Location_c", "Count_c")
names(recovered_totals)<-c("Location_r", "Count_r")
names(deaths_totals)<-c("Location_d", "Count_d")

max_rows<-max(nrow(confirmed_totals), nrow(recovered_totals), 
              nrow(deaths_totals))

# Wanted to use cbind.fill here, but can't because R...
if (nrow(confirmed_totals) < max_rows) {
  empty_df<-data.frame(matrix("NA", nrow = (max_rows - nrow(confirmed_totals)), 
                              ncol = 2))
  names(empty_df)<-c("Location_c", "Count_c")
  confirmed_totals<-rbind(confirmed_totals, empty_df)
}

if (nrow(recovered_totals) < max_rows) {
  empty_df<-data.frame(matrix("NA", nrow = (max_rows - nrow(recovered_totals)), 
                              ncol = 2))
  names(empty_df)<-c("Location_r", "Count_r")
  recovered_totals<-rbind(recovered_totals, empty_df)
}

if (nrow(deaths_totals) < max_rows) {
  empty_df<-data.frame(matrix("NA", nrow = (max_rows - nrow(deaths_totals)), 
                              ncol = 2))
  names(empty_df)<-c("Location_d", "Count_d")
  deaths_totals<-rbind(deaths_totals, empty_df)
}

total_ds<-cbind(confirmed_totals, recovered_totals, deaths_totals)

# Add Ranking column
total_ds<-cbind(data.frame(Rank=rownames(total_ds)), total_ds)

# Make Kabble Table
total_ds %>%
  kable(col.names = c("Rank", "Country", "Count", "Country", 
                      "Count", "Country", "Count"),
        caption="Table of Top Countries") %>%
  kable_styling("striped") %>%
  add_header_above(c(" " = 1, "Confirmations" = 2, 
                     "Recoveries" = 2, "Deaths" = 2)) %>%
  scroll_box(width = "100%", height = "600px")

```

# Zooming Into Our State
```{r obj4, message=FALSE, warning=FALSE, fig.width=10}
# Load Datasets
confirmed_ds<-read.csv("time_series_covid19_confirmed_US.csv", 
                       header=TRUE, stringsAsFactors=FALSE)
deaths_ds<-read.csv("time_series_covid19_deaths_US.csv", 
                    header=TRUE, stringsAsFactors=FALSE)

# Get totals per day through summation
confirmed_sum<-confirmed_ds %>%
  filter(Province_State=="California") %>%
  select(-(1:11)) %>%
  summarise_all(sum)

death_sum<-deaths_ds %>%
  filter(Province_State=="California") %>%
  select(-(1:12)) %>% 
  summarise_all(sum)

# Merge datasets into one and add column for categories
dat <- rbind(confirmed_sum, death_sum)
dat$dataset <- factor(c(rep("Confirmed", dim(confirmed_sum)[1]),
                        rep("Deaths", dim(death_sum)[1])))

data_long <- gather(dat, Dates, SumCases, -dataset, factor_key=TRUE)

# Create Plot
p1<-ggplot(data_long, aes(x=Dates, y=SumCases, color=dataset)) +
  scale_color_discrete(name= "California Total", 
                       breaks=c("Confirmed", "Deaths")) +
  geom_point() + ggtitle("California's Trajectory for COVID-19") + 
  scale_x_discrete(breaks=c("X2.1.20","X3.1.20","X4.1.20", "X5.1.20"),
                   labels=c("Feb", "Mar", "Apr", "May")) +
  labs(y= "Cases", x= "") +
  scale_y_continuous(breaks=pretty_breaks(n=5), 
                     labels=scales::comma)+
  geom_vline(xintercept="X3.19.20", linetype="dotted")

# Second scatter plot
top_confirmed_cities<-confirmed_ds %>%
  filter(Province_State=="California") %>%
  group_by(Admin2) %>%
  select(-(1:11)) %>%
  summarise_all(sum) %>%
  arrange_at(ncol(.), desc)

dat<-top_confirmed_cities[1:3,]
city_names<-c(dat[[1,1]], dat[[2,1]], dat[[3,1]])
data_long <- gather(dat, Dates, SumCases, -Admin2, factor_key=TRUE)

# Create Plot
p2<-ggplot(data_long, aes(x=Dates, y=SumCases, color=Admin2)) + 
  scale_color_discrete(name="Top Confirmed Cities", 
                       breaks=c(city_names[1], city_names[2], city_names[3])) +
  geom_point() +
  scale_x_discrete(breaks=c("X2.1.20","X3.1.20","X4.1.20", "X5.1.20"),
                   labels=c("Feb", "Mar", "Apr", "May")) +
  labs(y= "Cases", x = "Date") +
  scale_y_continuous(breaks=pretty_breaks(n=5), 
                     labels=scales::comma) +
   geom_vline(xintercept="X3.19.20", linetype="dotted")

plot_grid(p1, p2, nrow = 2, ncol = 1, align="hv")

```

# Digging Deeper
```{r obj5, message=FALSE, warning=FALSE, fig.width=10}
# Rename last column because R...
names(confirmed_ds)[ncol(confirmed_ds)]<-"Counts_c"
names(deaths_ds)[ncol(deaths_ds)]<-"Counts_d"

# Grab data for location population and counts on the last day
confirmed_data<-select(confirmed_ds, Admin2, Province_State, Counts_c)
deaths_data<-select(deaths_ds, Admin2, Province_State, Population, Counts_d)

# Join data frames based on location
total_data<-full_join(confirmed_data, deaths_data, 
                       by=c("Admin2", "Province_State"))

# Create Confirmations vs Population plot
p1<-ggplot(total_data, aes(x=Population, y=Counts_c)) +
  geom_point(color="blue") + ggtitle("Confirmations Vs. Population") +
  scale_x_log10(breaks=c(2^13, 2^16, 2^19, 2^22), labels=scales::comma, 
                         limits=c(2^12, 2^24)) +
  scale_y_log10(breaks=c(2^6, 2^10, 2^14, 2^18), labels=scales::comma, 
                limits=c(2^5, 2^19)) +
  labs(y= "Confirmation Counts", x= "Population")

# Create Deaths vs Confirmations plot
p2<-ggplot(total_data, aes(x=Counts_c, y=Counts_d)) +
  geom_point(color="red") + ggtitle("Deaths Vs. Confirmations") +
  scale_x_log10(breaks=c(2^8, 2^12, 2^16), labels=scales::comma, 
                         limits=c(2^7, 2^18)) +
  scale_y_log10(breaks=c(2^5, 2^8, 2^11, 2^14), labels=scales::comma, 
                limits=c(2^4, 2^16)) +
  labs(y= "Death Counts", x= "Confirmation Counts")

# Horizontially stack plots
plot_grid(p1, p2, nrow = 1, ncol = 2, align="hv")

```

# GitHub Log
#```{bash gitlog} 
#git log --pretty=format:"%nSubject: %s%nAuthor: %aN%nDate: %aD%nBody: %b"
#```
